version: '3.8'
services:
  chat-gateway:
    build:
      context: ./chat-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PUB_SUB_REDIS_URL=redis://redis:6379
      - CHAT_SERVICE_URL=http://localhost:8081/
      - USER_SERVICE_URL=http://localhost:8082/
    networks:
      - my-network-name
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/chat
    depends_on:
      - mongodb
    networks:
      - my-network-name
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/user
    depends_on:
      - mongodb
    networks:
      - my-network-name
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - cache:/data
    networks:
      - my-network-name
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    networks:
      - my-network-name

volumes:
  db:
  cache:
    driver: local

networks:
  my-network-name:
    driver: bridge
