version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/user
    depends_on:
      - mongodb
    networks:
      - node-network
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    networks:
      - node-network

volumes:
  db:

networks:
  node-network:
    driver: bridge
